### PR TITLE
split gotty into 3 parts-app, backends, and cli interface.

### PR DESCRIPTION
**Pull request by jizhilong**
Implements #128 

## What is this patch for?
The main goal of this patch is to make gotty a golang library, giving developers the ability to customize terminal generators without touching the protocol part.

## How I did it?
To achieve the above target, three main changes are made:

1.  add utils to generate cli flags and default option value from Option struct tags.
2. add two interface `ClientContextManger` and `ClientContext`, `ClientContextManger` provide instances of `ClientContext`, and a `ClientContext` instance provides a terminal's input&output, and the way to resize.
3. implement gotty's original function  based on a ptycommand backend,

## What's the *expected* impact of this change?
1. the original funciton of gottty **SHOULD NOT** be changed.
2. futures changes to how pty/command start and stop, or any other runtime behaviors should only require modifications to `backends/ptycommand`.
3. developers should be able to provide customized terminal backends.

### CODE REVIEW

**Comment by yudai** [comment]
Thank you for the PR!

Could you remove `backends/ptycommand/.command.go.swp`?

**Comment by jizhilong** [comment]
.swap files deleted and '*.swp' added to `.gitignore`

**Comment by yudai** [comment]
Thanks.

Could you update the commit 766deaa85c9c0fc7ea96af3aa54becbe1c6ab91e instead of adding a new commit? Since, it's important to keep the commit tree small.

**Comment by jizhilong** [comment]
sure, I'll squash the last 3 commits, since they are related.

**Comment by yudai** [comment]
Thanks. I'm working on some updates on this PR. will merge once I finish it.

**Comment by yudai** [comment]
Manually merged by #159 with some modification! Thanks!

**Pull request closed without merging**
