### PR TITLE
Add reuseport

### PR DESCRIPTION
**Pull request by oneumyvakin**
--reuse-port using SO_REUSEPORT socket flag to share same TCP port with other processes created under the same system user.
It can be used to provide racefree mechanism of binding TCP port when some front-end is open socket for gotty, start gotty process and than close own socket.

### CODE REVIEW

**Comment by yudai** [comment]
Hi, sorry for the delay to reply.

I'm afraid I cannot get the benefit of `SO_REUSEPORT`.  Why does the frontend need to open a port for gotty?

**Comment by oneumyvakin** [comment]
The main idea was in race-free port opening in multiuser system without some kind of syncing procedures. 
Well, it's not everyone need feature, and even in my case I've faced with side effects which can't to resolve.

**Comment by yudai** [comment]
As far as I know, on linux environments, if there are two or more processes that are listening at the same port with `SO_REUSEPORT`, the kernel randomly picks up a process from them. I therefore think this option doesn't work so well in your use case.
I'm afraid I cannot see a good use case to support multiple gotty processes on the same port. Random routing by the kernel doesn't make sense to me.

**Comment by oneumyvakin** [comment]
ok

**Comment by yudai** [comment]
Thanks for the feed back anyway!

**Pull request closed without merging**
