### PR TITLE
support for client certificate

### PR DESCRIPTION
**Pull request by freakhill**
I do not know go so please review thoroughly for gross errors.

### CODE REVIEW

**Comment by freakhill** [comment]
added support for client certificate, options:

verify_client_cert = true
client_cas = [ "/path/to/your/pem/ca/file/something.crt" ]

**Comment by freakhill** [comment]
wercker build crashed with 
    Setup environment failed:
    SyntaxError: Unexpected token u

**Comment by yudai** [comment]
Hi @freakhill , thank you for the PR.

I'm thinking if it's a good idea to implement all http stuff to gotty itself. Because there should be other requests like supporting the digest authentication, multiple users/passwords, HTTP2, and so on.
I besically want to keep gotty itself simple, so I want to offload those http stuff to other application like Nginx.

**Comment by yudai** [comment]
For example, [caddy](https://github.com/mholt/caddy) might be a good tool to use with gotty to support client certificates

**Comment by freakhill** [comment]
Well I use haproxy for that at work currently. But as gotty already supports HTTPS (server certificate) I thought it would be nice to complete with client certificate. 

With our without is fine though :)

Thank you for your thoughtful consideration :)

**Comment by yudai** [comment]
@freakhill Thank you for the reply.
Indeed this PR definitely make gotty more useful and I appreciate your PR.
However, there is also the UNIX philosophy "Make each program do one thing well", which I like. So I'm trying to find the best point that balances simplicity and the coverage of features.

I added some HTTP features like HTTPS as you mentioned, because I thought it was a kind of "basic" http feature. However, now I realized that there are so many http features that might be useful for each use case. 

Give me some time to find a good way to go. Thanks.

**Comment by yudai** [comment]
I decided to support client certs as a basic feature. Thank you for your PR!

**Comment by freakhill** [comment]
great!

**Pull request merged**
